# plugins/egerstudios/imagegallery/controllers/galleries/config_form.yaml

name: Gallery Form
form: ~/plugins/egerstudios/imagegallery/models/gallery/fields.yaml
modelClass: EgerStudios\ImageGallery\Models\Gallery

create:
    title: Create Gallery
    redirect: egerstudios/imagegallery/galleries/update/:id
    redirectClose: egerstudios/imagegallery/galleries

update:
    title: Edit Gallery
    redirect: egerstudios/imagegallery/galleries
    redirectClose: egerstudios/imagegallery/galleries

preview:
    title: Preview Gallery