# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Gallery

# Model Form Field configuration
form: $/egerstudios/imagegallery/models/gallery/fields.yaml

# Model Class name
modelClass: EgerStudios\ImageGallery\Models\Gallery

# Default redirect location
defaultRedirect: egerstudios/imagegallery/galleries

# Create page
create:
    title: backend::lang.form.create_title
    redirect: egerstudios/imagegallery/galleries/update/:id
    redirectClose: egerstudios/imagegallery/galleries

# Update page
update:
    title: backend::lang.form.update_title
    redirect: egerstudios/imagegallery/galleries
    redirectClose: egerstudios/imagegallery/galleries

# Preview page
preview:
    title: backend::lang.form.preview_title
